version: '3.8'

services:
  fastapi:
    build:
      context: .  # This should be the directory where your Dockerfile is located
    container_name: fastapi_app
    ports:
      - "8000:8000"
    environment:
      - MONGO_URL=mongodb://mongodb:27017
    depends_on:
      - mongodb
  
  mongodb:
    image: mongo:latest
    container_name: mongodb_OPA
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data: